name = "Modpack for Omsin's Create Server"
author = "Omsin"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c36f1e9206effb13c2e241a0020cc66fa93fab40b37f03361175ce5290d0cafb"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
